[project]
dependencies = [
  "psutil>=7.1.3",
  "pytest>=9.0.1",
]
description = "Add your description here"
name = "subset-sum-distinct-problem"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
